Feature/initialize project
ClintonYounge/My-Bookstore-Project pull request #1
Opened 2023-05-06 08:34 UTC by ClintonYounge

**Updates and added Features**
- Added individual book state, as well as a button to delete the book.
- Added a list to renders individual books.
- Added a form to create new books.
- Added navigation to link to the 2 routes you created.

2023-05-06 09:01 UTC, amon-cofie requested changes
Hi @ClintonYounge , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 💪 

<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights

🚀 You have a descriptive pull request summary
🚀 You have a professional Readme file
🚀 You have good commit messages
🚀 You used Gitflow properly
🚀 Your CSS files are well structured 👍 
🚀 You have no linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 09:01 UTC, amon-cofie commented on src/components/HomePage.js
> +    </div>
Your header is really well structured and you used the <Link> element very well in it 👍 🔥. However, since it is the header of your whole app, I think that putting it into your App.js file would be a better idea than putting it into the homepage alone. This way, the header shows up on every page of your app as it is supposed to, instead of only the homepage 😉

2023-05-06 10:07 UTC, ClintonYounge commented on src/components/HomePage.js
> +    </div>
@amon-cofie Great, thanks!

2023-05-06 10:57 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @ClintonYounge , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 10:57 UTC, ABDULALI3468 commented on src/components/HomePage.js
> +    </div>
As requested by the previous CR please consider adding the `<Header />` components in the `<App />` component so it shows on all the pages but remember to make it outside the routes.

### More clarification:-

```
import './App.css';
import { Route, Routes } from 'react-router-dom';
import CategoriesPage from './components/CategoriesPage';
import HomePage from './components/HomePage';
import Header from './components/Header.js'

function App() {
  return (
    <>
      <Header />
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/categories" element={<CategoriesPage />} />
      </Routes>
    </>
  );
}

export default App;
```

> After adding it in APP COMPONENT don't forget to remove it from the **Categories Page** and **Home Page.**

2023-05-06 17:56 UTC, MeqdamAlqudah approved these changes
Hi @ClintonYounge , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/74744787/236639568-cd4b4666-1c8a-400b-b44b-811e081fcc3f.png)

## Highligths 
:+1: Components structure.
:+1: Use of React routes.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 19:05 UTC, merged

2023-06-08 02:54 UTC, shella12 reviewed
Hi @ClintonYounge, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Project initialised using [Create React App](https://create-react-app.dev/) ✔️ 
- `react-router-dom` is present in package 👍 
-  2 `<Route>`s added: `/` and `/categories` 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 02:54 UTC, shella12 reviewed
Hi @ClintonYounge, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Project initialised using [Create React App](https://create-react-app.dev/) ✔️ 
- `react-router-dom` is present in package 👍 
-  2 `<Route>`s added: `/` and `/categories` 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._