Feature/styling
ClintonYounge/My-Bookstore-Project pull request #5
Opened 2023-06-15 22:02 UTC by ClintonYounge

**Update**
- Added styling to match Zeplin Template.

Find the template here- https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378

2023-06-15 22:38 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @ClintonYounge  :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Descriptive pull request.
✔️ Follow the correct Git flow.
✔️ Professional Readme.
✔️ Application is working fine.

## Required Changes ♻️

***Please kindly check the comments/review below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 22:38 UTC, Tufahel commented on src/styles/book.css
> +  background-color: rgb(77, 77, 255);
- [ ] The `background color` you have used for the buttons are not matching with the given design guideline. Kindly implement the given design guideline for styling. Please implement the color below for the background color of the button.
- ![image](https://github.com/ClintonYounge/My-Bookstore-Project/assets/60083437/9332020a-59a9-49c3-bd2e-860e12f347e2)

2023-06-15 22:38 UTC, Tufahel commented on src/styles/book.css
> +}
- [ ] The `background color` you have used for the buttons are not matching with the given design guideline. Kindly implement the given design guideline for styling. Please implement the color below for the background color of the button.
- ![image](https://github.com/ClintonYounge/My-Bookstore-Project/assets/60083437/9332020a-59a9-49c3-bd2e-860e12f347e2)

2023-06-15 22:38 UTC, Tufahel commented on src/styles/header.css
>  }
- ***Your Design***
![image](https://github.com/ClintonYounge/My-Bookstore-Project/assets/60083437/3ff20c5c-3768-442d-bce0-37f7c69290e2)

- ***Given Design***
![image](https://github.com/ClintonYounge/My-Bookstore-Project/assets/60083437/a74a505e-cb14-41ee-ae54-f346d64a0eeb)

- [ ] Color of the navigation menu such as: `Books` and `Categories` are not matching with the given design. From the given design you can see when a menu is `clicked` it becomes `darker` such as `Books`, and when a  menu is `unclicked` it becomes `lighter` such as `Categoies`. Kindly follow the design guideline for the color and use it in your design

2023-06-15 22:38 UTC, Tufahel commented on src/styles/header.css
>  }
- [ ] The `color` you have used for the `BookStore CMS` is not matching with the given design guideline. Kindly implement the given design guideline for styling. Please implement the color below for the color of the `Logo`.
- ![image](https://github.com/ClintonYounge/My-Bookstore-Project/assets/60083437/9332020a-59a9-49c3-bd2e-860e12f347e2)

2023-06-16 01:36 UTC, ClintonYounge commented
@Tufahel Thanks. Implemented all the requested changes.

2023-06-16 01:38 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @ClintonYounge,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-16 01:40 UTC, ClintonYounge commented
@Omar-Muhamad Incredible. Thanks for the review.

2023-06-16 01:44 UTC, merged